### ISSUE TITLE
OAuth2 is not working

### ISSUE THREAD

**Issue by lytex** [novoid/exchange2org#5]
My company started using OAuth some weeks ago and the script is no longer working.

<details>
  <summary>Full Traceback</summary>

```
ERROR    UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx
Retry: 0
Waited: 10
Timeout: 120
Session: 24660
Thread: 139687554021184
Auth type: <requests.auth.HTTPBasicAuth object at 0x7f0b86a30af0>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f0b86a309a0>
Allow redirects: False
Streaming: False
Response time: 0.1890680180003983
Status code: 401
Request headers: {'User-Agent': 'exchangelib/4.4.0 (python-requests/2.26.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '463', 'Authorization': 'Basic anVsb3BlemNAYWNjaW9uYS5jb206QWN0aXZpdHlXYXRjaC0xMjM='}
Response headers: {'Server': 'Microsoft-IIS/10.0', 'request-id': 'c9174f89-17b7-df9b-b006-fff12e1f60b2', 'Alt-Svc': 'h3=":443",h3-29=":443"', 'X-CalculatedFETarget': 'DB8PR09CU001.internal.outlook.com', 'X-BackEndHttpStatus': '401, 401', 'Set-Cookie': 'exchangecookie=756961bcade04553869ddc02c545003a; expires=Wed, 16-Nov-2022 12:50:42 GMT; path=/; secure; HttpOnly', 'X-FEProxyInfo': 'DB8PR09CA0012.EURPRD09.PROD.OUTLOOK.COM', 'X-CalculatedBETarget': 'DB7PR05MB5785.eurprd05.prod.outlook.com', 'X-RUM-Validated': '1', 'X-BeSku': 'WCS5', 'X-DiagInfo': 'DB7PR05MB5785', 'X-BEServer': 'DB7PR05MB5785', 'X-Proxy-RoutingCorrectness': '1', 'X-Proxy-BackendServerStatus': '401', 'X-FEServer': 'DB8PR09CA0012, MR1P264CA0016', 'X-FirstHopCafeEFZ': 'MRS', 'X-Powered-By': 'ASP.NET', 'WWW-Authenticate': 'Basic Realm=""', 'Date': 'Tue, 16 Nov 2021 12:50:42 GMT', 'Content-Length': '0'}
Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>julopezc@acciona.com</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>'
Response XML: b''
CRITICAL Error occured while trying to set up connection with the exchange server "outlook.office365.com":
```

```python
Traceback (most recent call last):
  File "/home/julian/code/exchange2org/exchange2org/__init__.py", line 426, in <module>
    main()
  File "/home/julian/code/exchange2org/exchange2org/__init__.py", line 413, in main
    exchange2org = Exchange2Org(exchange2orgconfig, logging.getLogger())
  File "/home/julian/code/exchange2org/exchange2org/__init__.py", line 157, in __init__
    self.account = exchangelib.Account(self.config.PRIMARY_SMTP_ADDRESS, config=self.exchange_config, autodiscover=False, access_type=exchangelib.DELEGATE)
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/account.py", line 133, in __init__
    self.version = self.protocol.version
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/protocol.py", line 452, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/version.py", line 229, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/services/resolve_names.py", line 36, in call
    for elem in self._chunked_get_elements(
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/services/common.py", line 198, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/services/common.py", line 216, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/services/common.py", line 182, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/services/common.py", line 296, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/services/common.py", line 251, in _get_response
    r, session = post_ratelimited(
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/util.py", line 874, in post_ratelimited
    protocol.retry_policy.raise_response_errors(r)  # Always raises an exception
  File "/home/julian/.local/lib/python3.9/site-packages/exchangelib/protocol.py", line 671, in raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx
```
</details>

It seems one has to register the application in Azure:
http://fendertech.blogspot.com/2021/03/using-exchangelib-to-test-ews-oauth2.html
Here's the docs on OAuth:
https://ecederstrand.github.io/exchangelib/#oauth-authentication

I'll get on this when I have the time, but I'm not sure how to proceed with it though.

Do I register the app with my account? Do you want to set it up yourself @novoid?

**Comment by novoid** [comment]
Hi @lytex,

I'm sorry, I can't help any more. I don't have access to Exchange any more. I was lucky that the auth process was working for me back then. I don't have deeper knowledge on Exchange or its auth processes.

If you do find a solution, I'll add it to this repository. However, I can not support in finding a solution any more as my current company is not using Microsoft infrastructure.

**Comment by lytex** [comment]
I've moved to a setup using [evolution](https://wiki.gnome.org/Apps/Evolution), which is able to export daily my calendar to a .ics file and then I'm using [organised-exchange](https://github.com/ettomatic/organised-exchange) to export it to an org file.

I'll reopen this issue if I happen to work on it again.

**Comment by novoid** [comment]
> I've moved to a setup using [evolution](https://wiki.gnome.org/Apps/Evolution)

Welcome to the club: https://karl-voit.at/2021/06/01/Thunderbird-to-Evolution/
